# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f69b8538fd3f3a654324c612378a9f843baab0ad4e236d762e4823d166a557af78121390ed8315148feb0953b5704f2796773cf26faca03c65024efe5fb3b50e

test:
  secret_key_base: 1fc30753cf8f0c16295f797ef64431d7492f1477327aa80ce9a58c738442dd6dfe9c09c7ca010920359d122f7820fb3c6c2b3c692aa0c7f3fde6bce23e7b422a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
